    cfonts 'LEGAL|WAR ROOM' -f pallet -g yellow,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -g green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g red,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -g cyan,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -g blue,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g green,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -g red,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -g red,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -g yellow,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -g green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -g green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -g red,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -g cyan,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -g yellow,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g red,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -g red,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -g magenta,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f pallet -g green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f tiny -g red,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -g red,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -g blue,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f pallet -g magenta,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -g green,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -g blue,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g cyan,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -g green,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -g red,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -g yellow,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f tiny -g green,red --align "center"
    
    # Transition combinations (smooth flows)
    cfonts 'LEGAL|WAR ROOM' -f pallet -t yellow,red,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -t green,cyan,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -t red,magenta,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -t cyan,magenta,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -t blue,cyan,green --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -t green,yellow,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -t red,yellow,magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -t magenta,cyan,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -t yellow,green,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -t blue,magenta,red --align "center"
    
    # Single color classics (when you want clean)
    cfonts 'LEGAL|WAR ROOM' -f pallet -c cyan, --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -c blueBright --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -c yellowBright --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -c blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -c green --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -c whiteBright --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -c blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f pallet -c cyanBright --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -c yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -c whiteBright --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -c magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -c green --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -c red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -c cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -c blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f tiny -c green --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -c red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -c magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f pallet -c yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -c green --align "center"

    # Background combinations (the fire ones)
    cfonts 'LEGAL|WAR ROOM' -f block -c white -b blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple -c yellow -b black --align "center"
    cfonts 'LEGAL|WAR ROOM' -f pallet -c cyan -b magenta --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -c green -b red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -c white -b cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -c blue -b yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -c red -b blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -c magenta -b green --align "center"
    
    # Size variations (huge impact)
    cfonts 'LEGAL|WAR ROOM' -f huge -c cyan, --align "center"
    cfonts 'LEGAL|WAR ROOM' -f massive -c red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f tiny -c green --align "center"
    
    # Special effects (the wild ones)
    cfonts 'LEGAL|WAR ROOM' -f chrome -c rainboW --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -c candy --align "center"
    cfonts 'LEGAL|WAR ROOM' -f simple3d -c system --align "center"
    
    # More gradient madness
    cfonts 'LEGAL|WAR ROOM' -f pallet -g blue,cyan --align "center"
    cfonts 'LEGAL|WAR ROOM' -f slick -g red,yellow --align "center"
    cfonts 'LEGAL|WAR ROOM' -f shade -g magenta,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f chrome -g yellow,red --align "center"
    cfonts 'LEGAL|WAR ROOM' -f grid -g green,blue --align "center"
    cfonts 'LEGAL|WAR ROOM' -f block -g cyan,yellow --align "center"